### ISSUE TITLE
Adding Actions

### ISSUE THREAD

**Issue by egekorkan** [mozilla-iot/virtual-things-adapter#38] opened 2019-09-18 02:01 UTC
It seems that this adapter can allow to add only properties. If it can generate properties with random responses, can't it be done for actions the same way as well?

**Comment by mrstegeman** [comment] 2019-09-18 02:07
Theoretically, but what would the actions actually do? Actions do not inherently have a specific output, or any output, for that matter.

**Comment by egekorkan** [comment] 2019-09-18 04:16
I had thought it for the purposes of learning how to use inputs of different kind and also if the GUI enables it, there could be a completion time parameter which would allow experimenting with the action queues properly

**Comment by mrstegeman** [comment] 2019-09-18 20:17
So, on the back-end, the action would do nothing at all other than complete after some specified amount of time?

The Virtual Actions & Events thing already accepts inputs in a variety of supported formats, so is there something else you're hoping to gain from this?

For reference, I added the concept of custom things for 2 reasons:
1. To allow us to reproduce bugs, e.g. an issue due to a specific property name.
2. Our users use the virtual things for a variety of control purposes, so custom things allow them to have an arbitrary number of on/off switches, for example.

**Comment by egekorkan** [comment] 2019-09-19 01:29
> The Virtual Actions & Events thing already accepts inputs in a variety of supported formats, so is there something else you're hoping to gain from this?

So this is why I wanted to have the actions but putting the inputs I want. I have checked this Thing already and the actions are only created and never(?) completed or change status.

Custom things with actions would have the same use case of custom things with properties. It would allow to reproduce bugs for specific actions and for users to add an arbitrary amount of actions. The timing feature request is just a nice to have in this regard but I think it is very valuable for testing the client applications.

**Comment by mrstegeman** [comment] 2020-07-14 19:12
This doesn't seem to add a lot of value. Closing.

**Closed by mrstegeman** 2020-07-14 19:12 UTC
